config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :recarga_saldos

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  root to: "home#index"
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include Controleable
  before_action :coleccion_inicial, only: %i[index excel_index]
  before_action :validar_usuario_edicion, only: %i[edit destroy]
  prepend_before_action :procesar_parametros, only: %i[create update]

  def coleccion_inicial
    params[:q] ||= {}
    @coleccion = Rol.ransack(params[:q])
    respond_to do |formato|
      formato.html do
        @registros = @coleccion.result.page(params[:page])
      end
      formato.xlsx do
        @registros = @coleccion.result
      end
    end
  end

  def index
    authorize!(:index, :Roles)
    @params_permit = params[:q].present? ? {q: params[:q] .permit! } : {}
    render template: "roles/index",  layout: 'layouts/application'
  end

  def new
    authorize!(:new, :Roles)
    render template: 'roles/form', layout: 'layouts/application'
  end

  def edit
    authorize!(:edit, :Roles)
    render template: 'roles/form', layout: 'layouts/application'
  end

  def create
    begin
      if @registro.save!
        flash[:notice] = "El registro fue guardado exitosamente"
        redirect_to action: :index
      end
    rescue StandardError => e
      flash[:error] = "Ocurrio un error al guardar los datos" if flash.now[:error].blank?
      render template: "roles/form", layout: "layouts/application"
    end
  end

  def update
    begin
      if @registro.save!
        flash[:notice] = "El registro fue actualizado exitosamente"
        redirect_to action: :index
      end
    rescue StandardError => e
      flash[:error] = "Ocurrio un error al actualizar los datos" if flash.now[:error].blank?
      render template: "roles/form", layout: "layouts/application"
    end
  end

  def destroy
    authorize!(:destroy, :Roles)
    begin
      flash[:notice] = "El registro ha sido eliminado exitosamente" if @registro.destroy
    rescue StandardError => e
      flash[:alert] = e.message
    end
    redirect_to action: :index, search: params[:q]
  end

  def excel_index
    respond_to do |formato|
      formato.xlsx do
        render(
          xlsx: "excel_index",
          filename: "Roles del sistema - #{Date.today}.xlsx"
        )
      end
    end
  end

  private

    def nombre_recurso
      "Rol"
    end

    def rol_params
      params.require(:rols)
             .permit(:id, :nombre,
                     rol_accion_attributes: [:id, :rol_id, :recurso_id, :accion_id, :marcado])
    end

    def procesar_parametros
      params[:rols][:rol_accion_attributes] = []
      recursos_roles = params[:permisos] || []
      recursos_roles.each  do |recurso|
        llaves_recurso = recurso.first.split("_")
        params[:rols][:rol_accion_attributes].push(id: llaves_recurso[Rol::ID] ,rol_id: llaves_recurso[Rol::ROL_ID],
              recurso_id: llaves_recurso[Rol::RECURSO_ID], accion_id: llaves_recurso[Rol::ACCION_ID], marcado: recurso.last.to_boolean  )
      end
    end

    def validar_usuario_edicion
      redirect_to roles_path , alert: "No se puede editar/eliminar el usuario Administrador." if params[:id].to_i == Rol::ADMINISTRADOR
    end

    alias :params_permit :rol_params
end

app/views/roles/_filtros.html.erb
<div class="col-lg-6 text-left">
    <button class="btn btn-lg btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="btn-inner--icon"><i class="fas fa-search"></i></span>
            <span class="btn-inner--text">Filtros</span>
    </button>

    <div class="dropdown-menu w-60">
        <%= search_form_for @coleccion, url: roles_path, class: "px-4 py-3 text-center" do |formulario| %>
            <div class="form-group text-left">
                <%= label_tag(:nombre_cont, "Nombre:") %>
                <%= text_field_tag "q[nombre_cont]", params[:q][:nombre_cont], class: "form-control" %>
            </div>
            <%= formulario.submit class: "btn btn-primary text-center" %>
            <%= link_to "Quitar Filtros", roles_path, class: "btn btn-danger text-center" %>
        <% end %>
     </div>
</div>

app/views/roles/_roles_formulario.html.erb
<% presenter = RolPresenter.new(@registro) %>
<div class="row">
    <div class="col-lg-12">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Información del Rol</h3>
                </div>
                <div class="card-body">
                    <%= hidden_field(:rols, :id, :value => @registro.id) %>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Nombre</label>
                        <%= text_field(:rols, :nombre, class: "form-control", id: "nombre", value: @registro.nombre) %>
                        <p class="text-danger"><%= @registro.errors[:nombre].first %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row mb-3 mt-3">
    <nav id="menu_tabs" class="nav nav-pills nav-justified container-fluid">
        <% TipoRecurso.all.each do |tipo_recurso| %>
            <a class="nav-item nav-link" data-toggle="tab" href="#<%= tipo_recurso.nombre %>"><%= tipo_recurso.nombre %></a>
        <% end %>
    </nav>

    <div class="tab-content container-fluid">
        <% TipoRecurso.all.each do |tipo_recurso| %>
            <% recursos_asociados = Recurso.where(tipo_recurso_id: tipo_recurso.id) %>
            <div id="<%= tipo_recurso.nombre %>" class="tab-pane fade mt-4">
                <div class ="card">
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th class="sort">Recurso</th>
                                    <% Accion.all.each do |accion| %>
                                        <th class="sort"><%= accion.nombre %> </th>
                                    <% end %>
                                </tr>
                            </thead>
                            <tbody class="list">
                                <% recursos_asociados.each do |recurso| %>
                                    <tr>
                                        <td><%= recurso.nombre %></td>
                                        <% Accion.all.each do |accion| %>
                                            <% recurso_accion_id = "#{presenter.encontrar_identificador(recurso.id, accion.id)}_#{@registro.id}_#{recurso.id}_#{accion.id}" %>
                                            <% permiso_marcado = presenter.permiso_activo(recurso.id, accion.id) %>
                                            <td>
                                                <div class="custom-control custom-checkbox mb-3">
                                                    <%= check_box("permisos", recurso_accion_id, { class: "custom-control-input", checked: permiso_marcado }, Rol::MARCADO, Rol::DESMARCADO) %>
                                                    <label class="custom-control-label" for="permisos_<%= recurso_accion_id %>"></label>
                                                </div>
                                            </td>
                                        <% end %>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/roles/form.html.erb
<% content_for :titulo_seccion do %>
  Roles
<% end %>

<%= render "shared/flash", flash: flash %>
<%= javascript_include_tag "rol" %>

<%= render partial: 'roles/roles_formulario', layout: "layouts/formulario",
    locals: {
        registro: @registro,
        url: @url
    }
%>

app/views/roles/index.html.erb
<% content_for :titulo_seccion do %>
  Roles
<% end %>

<div class="col-lg-12 col-12">
   <div class="row">
      <%= render 'roles/filtros' %>
      <div class="col-lg-6 text-right">
         <%= link_to "Descargar Excel", excel_index_roles_path(@params_permit), class: "btn btn-lg btn-success" %>
         <%= link_to "Crear Recurso", new_role_path, class: "btn btn-lg btn-neutral" %>
      </div>
   </div>
</div>

<div class="container-fluid mt-3">
   <div class="row">
      <div class="col pl-0 pr-0">
         <div class="card">
            <div class="card-header">
               <h3 class="mb-0">Roles registrados</h3>
            </div>
            <div class="table-responsive">
               <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                     <tr>
                        <th class="sort"><%= sort_link(@coleccion, :id, "ID") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :nombre, "Nombre") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :created_at, "Creado El") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :updated_at, "Actualizado El") %></th>
                        <th>Actualizar</th>
                        <th>Eliminar</th>
                     </tr>
                  </thead>
                  <tbody class="list">
                    <% @registros.each do |rol| %>
                     <tr>
                        <td><%= rol.id %></td>
                        <td><%= rol.nombre %></td>
                        <td><%= rol.created_at %></td>
                        <td><%= rol.updated_at %></td>
                        <td>
                           <%= link_to edit_role_path(rol), class: "btn btn-icon btn-primary" do %>
                              <i class="ni ni-align-left-2"></i>
                           <% end %>
                        </td>
                        <td>
                           <%= link_to role_path(rol), class: "btn btn-icon btn-danger", method: :delete do %>
                              <i class="ni ni-scissors"></i>
                           <% end %>
                        </td>
                     </tr>
                    <% end %>
                  </tbody>
               </table>
            </div>
            <div class="card-footer py-4">
             <%= paginate @registros %>
             <%= page_entries_info @registros %>
            </div>
         </div>
      </div>
   </div>
</div>