config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :recarga_saldos

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  root to: "home#index"
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  ACTIVO = 1
  INACTIVO = 0
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :usuario, presence: true,  length: {minimum: 4, maximum: 10}
  validates :telefono, presence: true, numericality: true, length: {is: 8}
  validates_uniqueness_of :usuario
  validates_uniqueness_of :telefono
  validates :usuario, format: { without: /\s/, message: "No puede haber espacios en blancos" }

  def active_for_authentication?
    super && self.activo
  end

  def inactive_message
    "Tu cuenta ha sido desactivada."
  end
end

app/controllers/usuarios/confirmations_controller.rb
# frozen_string_literal: true

class Usuarios::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/usuarios/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Usuarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/usuarios/passwords_controller.rb
# frozen_string_literal: true

class Usuarios::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/usuarios/registrations_controller.rb
# frozen_string_literal: true

class Usuarios::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/usuarios/sessions_controller.rb
# frozen_string_literal: true

class Usuarios::SessionsController < Devise::SessionsController
  layout false
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/usuarios/unlocks_controller.rb
# frozen_string_literal: true

class Usuarios::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
    include Controleable

    before_action :validar_captcha, only: %i[create update]
    before_action :authenticate_usuario!
    before_action :coleccion_inicial, only: %i[index excel_index]

    def coleccion_inicial
        params[:q] ||= {}
        @coleccion = Usuario.ransack(params[:q])
        respond_to do |formato|
            formato.html do
                @registros = @coleccion.result.page(params[:page])
            end
            formato.xlsx do
                @registros = @coleccion.result
            end
        end
    end

    def index
        authorize!(:read, :Usuario)
        @params_permit = params[:q].present? ? {q: params[:q] .permit! } : {}
        render template: "usuarios/index",  layout: "layouts/application"
    end

    def new
        authorize!(:create, :Usuario)
        render template: "usuarios/form", layout: "layouts/application"
    end

    def show
        authorize!(:update, :Usuario)
        render template: "usuarios/form", layout: "layouts/application"
    end

    def edit
        authorize!(:update, :Usuario)
        render template: "usuarios/form", layout: "layouts/application"
    end

    def excel_index
        respond_to do |formato|
            formato.xlsx do
                render(
                    xlsx: "excel_index",
                    filename: "Usuarios del sistema - #{Date.today}.xlsx"
                )
            end
        end
    end

    def create
        begin
            if @registro.save!
                    flash[:notice] = "El registro fue guardado exitosamente"
                    redirect_to action: :index
            end
        rescue StandardError => e
            flash[:error] = "Ocurrio un error al guardar los datos" if flash.now[:error].blank?
            render template: "usuarios/form", layout: "layouts/application"
        end
    end

    def update
        begin
            if @registro.save!
                flash[:notice] = "El registro fue actualizado exitosamente"
                redirect_to action: :index
            end
        rescue StandardError => e
            flash[:error] = "Ocurrio un error al actualizar los datos" if flash.now[:error].blank?
            render template: "usuarios/form", layout: "layouts/application"
        end
    end

    def destroy
        authorize!(:destroy, :Usuario)
        begin
            flash[:notice] = "El registro ha sido eliminado exitosamente" if @registro.destroy
        rescue StandardError => e
            flash[:error] = e.message
        end

        redirect_to action: :index, search: params[:q]
    end

    private

    def nombre_recurso
        "Usuario"
    end

    def usuario_params
        params.require(:usuarios).permit(:id, :email, :password, :usuario, :telefono, :es_admin,
                                         :rols_id, :activo)
    end

    alias :params_permit :usuario_params

    def validar_captcha
        unless verify_recaptcha
            render template: "usuarios/form"
        end
    end
end

app/views/usuarios/_filtros.html.erb
<div class="col-lg-6 text-left">
    <button class="btn btn-lg btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="btn-inner--icon"><i class="fas fa-search"></i></span>
            <span class="btn-inner--text">Filtros</span>
    </button>

    <div class="dropdown-menu w-60">
        <%= search_form_for @coleccion, url: usuarios_path, class: "px-4 py-3 text-center" do |formulario| %>
            <div class="form-group text-left">
                <%= label_tag(:email_cont, "Correo:") %>
                <%= text_field_tag "q[email_cont]", params[:q][:email_cont], class: "form-control" %>
            </div>
            <div class="form-group text-left">
                <%= label_tag(:nombre_cont, "Nombre:") %>
                <%= text_field_tag "q[usuario_cont]", params[:q][:nombre_cont], class: "form-control" %>
            </div>
            <%= formulario.submit class: "btn btn-primary text-center" %>
            <%= link_to "Quitar Filtros", usuarios_path, class: "btn btn-danger text-center" %>
        <% end %>
     </div>
</div>

app/views/usuarios/_usuarios_formulario.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Información del Usuario</h3>
                </div>
                <div class="card-body">
                    <%= hidden_field(:usuarios, :id, :value => @registro.id) %>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Correo</label>
                        <%= text_field(:usuarios, :email, class: "form-control", id: "correo", value: @registro.email) %>
                        <p class="text-danger"><%= @registro.errors[:email].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Contraseña</label>
                        <%= password_field(:usuarios, :password, class: "form-control") %>
                        <p class="text-danger"><%= @registro.errors[:password].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Usuario</label>
                        <%= text_field(:usuarios, :usuario, class: "form-control", id: "nombre", value: @registro.usuario) %>
                        <p class="text-danger"><%= @registro.errors[:usuario].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Telefono</label>
                        <%= text_field(:usuarios, :telefono, class: "form-control", id: "telefono", value: @registro.telefono) %>
                        <p class="text-danger"><%= @registro.errors[:telefono].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Rol</label>
                        <%= select_tag "usuarios[rols_id]", options_from_collection_for_select(Rol.all, :id, :nombre, @registro.rols_id ),
                            class: "form-control selectpicker", "data-live-search": "true" %>
                        <p class="text-danger"><%= @registro.errors[:rols_id].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="nombre">Estado</label>
                        <%= select_tag "usuarios[activo]", options_for_select([["Activo", Usuario::ACTIVO], ["Inactivo", Usuario::INACTIVO]], "#{@registro.activo.to_i}"),
                            class: "form-control selectpicker", "data-live-search": "true" %>
                        <p class="text-danger"><%= @registro.errors[:rols_id].first %></p>
                    </div>

                    <div class="form-group">
                      <%= recaptcha_tags %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/usuarios/form.html.erb
<% content_for :titulo_seccion do %>
  Usuarios
<% end %>

<%= render "shared/flash", flash: flash %>
<%= render partial: 'usuarios/usuarios_formulario', layout: "layouts/formulario",
    locals: {
        registro: @registro,
        url: @url
    }
%>

app/views/usuarios/index.html.erb
<% content_for :titulo_seccion do %>
  Usuarios
<% end %>

<div class="col-lg-12 col-12">
   <div class="row">
      <%= render 'usuarios/filtros' %>
      <div class="col-lg-6 text-right">
         <%= link_to "Descargar Excel", excel_index_usuarios_path(@params_permit), class: "btn btn-lg btn-success" %>
         <%= link_to "Crear Recurso", new_usuario_path, class: "btn btn-lg btn-neutral" %>
      </div>
   </div>
</div>

<div class="container-fluid mt-3">
   <div class="row">
      <div class="col pl-0 pr-0">
         <div class="card">
            <div class="card-header">
               <h3 class="mb-0">Usuarios registrados</h3>
            </div>
            <div class="table-responsive">
               <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                     <tr>
                        <th class="sort"><%= sort_link(@coleccion, :id, "ID") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :email, "Correo") %></th>
                        <th>Usuario</th>
                        <th>Saldo Recarga</th>
                        <th>Estado</th>
                        <th>Creado El</th>
                        <th>Actualizado El</th>
                        <th>Actualizar</th>
                        <th>Eliminar</th>
                     </tr>
                  </thead>
                  <tbody class="list">
                    <% @registros.each do |usuario| %>
                     <tr>
                        <td><%= usuario.id %></td>
                        <td><%= usuario.email %></td>
                        <td><%= usuario.usuario %></td>
                        <td><%= usuario.saldo_recarga %></td>
                        <td><%= I18n.t(usuario.activo) %></td>
                        <td><%= usuario.created_at %></td>
                        <td><%= usuario.updated_at %></td>
                        <td>
                           <%= link_to edit_usuario_path(usuario), class: "btn btn-icon btn-primary" do %>
                              <i class="ni ni-user-run"></i>
                           <% end %>
                        </td>
                        <td>
                           <%= link_to usuario_path(usuario), class: "btn btn-icon btn-danger", method: :delete do %>
                              <i class="ni ni-basket"></i>
                           <% end %>
                        </td>
                     </tr>
                    <% end %>
                  </tbody>
               </table>
            </div>
            <div class="card-footer py-4">
             <%= paginate @registros %>
             <%= page_entries_info @registros %>
            </div>
         </div>
      </div>
   </div>
</div>