config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :recarga_saldos

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  root to: "home#index"
end

app/views/layouts/_formulario.html.erb
<%= form_for(registro, url: url, html: { multipart: true }) do |formulario| %>
  <%= yield %>
  <%= formulario.submit "Guardar", class: "btn btn-primary btn-lg mb-3" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for :titulo_seccion %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
      <div class="scrollbar-inner">
        <div class="sidenav-header d-flex align-items-center">
          <a class="navbar-brand" href="#">
            <%= image_tag "logo_empresa_default", class:"navbar-brand-img" %>
          </a>
          <div class="ml-auto">
            <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </div>
          </div>
        </div>
        <div class="navbar-inner">
          <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <ul class="navbar-nav">
              <%= render 'menu/menu_lista' %>
            </ul>
          </div>
        </div>
      </div>
  </nav>
  <div class="main-content" id="panel">
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul id="titulo_seccion" class="ml-auto ml-md-0 mb-0 pl-0 text-white display-4">
            <%= content_for :titulo_seccion %>
          </ul>
          <ul class="navbar-nav align-items-center ml-md-auto">
            <li>
            </li>
            <li class="nav-item d-xl-none">
              <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </div>
            </li>
            <li class="nav-item d-sm-none">
              <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                <i class="ni ni-zoom-split-in"></i>
              </a>
            </li>
          </ul>
          <ul class="navbar-nav align-items-center ml-auto ml-md-0">
            <li class="nav-item dropdown">
              <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <%= image_tag "user.png", class:"navbar-brand-img" %>
                  </span>
                  <div class="media-body ml-2 d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold"><%= current_usuario.email %></span>
                  </div>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a href="<%= edit_usuario_url(current_usuario) %>" class="dropdown-item">
                  <i class="ni ni-single-02 text-primary"></i>
                  <span>Mi Usuario</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="<%= destroy_usuario_session_path %>" class="dropdown-item">
                  <i class="ni ni-user-run text-orange"></i>
                  <span>Cerrar Sesión</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid mt-2">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <span class="alert-icon"><i class="ni ni-check-bold"></i></span>
          <span class="alert-text"><%= notice %></span>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <span class="alert-icon"><i class="ni ni-sound-wave"></i></span>
          <span class="alert-text"><%= alert %></span>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
  </body>
</html>