config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }, path_prefix: "auth"

  resources :home
  resources :recarga_saldos

  resources :roles do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  resources :usuarios do
    get :excel_index, on: :collection, defaults: { :format => "xlsx" }
  end

  root to: "home#index"
end

app/models/recarga_saldo.rb
class RecargaSaldo < ApplicationRecord
    belongs_to :usuario
    belongs_to :catalogo_recarga

    validates :telefono, presence: true, numericality: true, length: {is: 8}
    validates :catalogo_recarga, presence: true
    validate :validar_telefono
    before_save :asignar_valores
    after_commit :calcular_promociones

    def validar_telefono
        usuario = Usuario.find_by_id(usuario_id)
        if usuario.telefono != telefono
            raise StandardError.new "Telefono no pertenece al Usuario." 
        end 
    end

    def calcular_promociones
        rango_fecha = Date.today.beginning_of_month...Date.today.end_of_month
        recargas = RecargaSaldo.where(fecha: rango_fecha, catalogo_recarga_id: self.catalogo_recarga_id, 
                                      telefono: self.telefono)
        promocion_recarga_id = case self.catalogo_recarga_id    
        when CatalogoRecarga::RECARGA_20   
            if recargas.size == CatalogoRecarga::NUMERO_RECARGA_20
                CatalogoRecarga::RECARGA_10
            end
        when CatalogoRecarga::RECARGA_50
            if recargas.size == CatalogoRecarga::NUMERO_RECARGA_50
                CatalogoRecarga::RECARGA_20
            end
        when CatalogoRecarga::RECARGA_100
            if recargas.size == CatalogoRecarga::NUMERO_RECARGA_100
                CatalogoRecarga::RECARGA_50
            end
        end
        unless promocion_recarga_id.nil?
            usuario = Usuario.find_by_id(usuario_id)
            catalogo_recarga = CatalogoRecarga.find(promocion_recarga_id)       
            monto_final = usuario.saldo_recarga + catalogo_recarga.monto 
            promocion = RecargaSaldo.new(fecha: Date.today, usuario_id: self.usuario_id, catalogo_recarga_id: promocion_recarga_id,
                                         saldo_inicial: usuario.saldo_recarga, saldo_final: monto_final, telefono: self.telefono )
            promocion.save!
        end
    end

    def asignar_valores
        # Encontramos el usuario y procedemos a actualizar los datos
        usuario = Usuario.find_by_id(usuario_id)
        self.usuario_id = usuario.id
        self.telefono = usuario.telefono        
        self.saldo_inicial = self.usuario.saldo_recarga
        self.saldo_final = saldo_inicial + catalogo_recarga.monto
        self.fecha = Date.today
        usuario.saldo_recarga =  saldo_final
        usuario.save!
    end
end

app/controllers/recarga_saldos_controller.rb
class RecargaSaldosController < ApplicationController
  include Controleable
  before_action :authenticate_usuario!
  before_action :coleccion_inicial, only: %i[index]

  def coleccion_inicial
    params[:q] ||= {}
    @coleccion = RecargaSaldo.ransack(params[:q])
    respond_to do |formato|
      formato.html do
        @registros = @coleccion.result.page(params[:page])
      end
    end
  end

  def index
    authorize!(:read, :Recarga)
    @params_permit = params[:q].present? ? {q: params[:q] .permit! } : {}
    render template: "recarga_saldos/index",  layout: "layouts/application"
  end

  def new
    authorize!(:create, :Recarga)
    render template: "recarga_saldos/form", layout: "layouts/application"
  end

  def create
    begin
      if @registro.save!
        flash[:notice] = "El registro fue guardado exitosamente"
        redirect_to action: :index
      end
    rescue StandardError => e
      flash[:error] = e
      render template: "recarga_saldos/form", layout: "layouts/application"
    end
  end

  private

    def nombre_recurso
      "RecargaSaldo"
    end

    def recarga_params
      params.require(:recarga_saldo).permit(:id, :telefono, :catalogo_recarga_id, :usuario_id)
    end

    alias :params_permit :recarga_params
end

app/views/recarga_saldos/_filtros.html.erb
<div class="col-lg-6 text-left">
    <button class="btn btn-lg btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="btn-inner--icon"><i class="fas fa-search"></i></span>
            <span class="btn-inner--text">Filtros</span>
    </button>

    <div class="dropdown-menu w-60">
        <%= search_form_for @coleccion, url: recarga_saldos_path, class: "px-4 py-3 text-center" do |formulario| %>
            <div class="form-group text-left">
                <%= label_tag(:nombre_cont, "Nombre:") %>
                <%= text_field_tag "q[nombre_cont]", params[:q][:nombre_cont], class: "form-control" %>
            </div>
            <%= formulario.submit class: "btn btn-primary text-center" %>
            <%= link_to "Quitar Filtros", recarga_saldos_path, class: "btn btn-danger text-center" %>
        <% end %>
     </div>
</div>

app/views/recarga_saldos/_recargas_formulario.html.erb
<div class="row">
    <div class="col-lg-6">
        <div class="card-wrapper">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Información de la Recarga</h3>
                </div>
                <div class="card-body">
                    <%= hidden_field(:recarga_saldo, :id, :value => @registro.id) %>
                    <%= hidden_field(:recarga_saldo, :usuario_id, :value => current_usuario.id) %>
                    <div class="form-group">
                        <label class="form-control-label" for="telefono">Telefono</label>
                        <%= text_field(:recarga_saldo, :telefono, class: "form-control", id: "telefono", value: @registro.telefono) %>
                        <p class="text-danger"><%= @registro.errors[:telefono].first %></p>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="monto">Paquetes de Recargas</label>
                        <%= select_tag "recarga_saldo[catalogo_recarga_id]", options_from_collection_for_select(CatalogoRecarga.all, :id, :monto, @registro.catalogo_recarga_id ),
                            class: "form-control selectpicker", "data-live-search": "true" %>
                        <p class="text-danger"><%= @registro.errors[:catalogo_recarga_id].first %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/recarga_saldos/form.html.erb
<% content_for :titulo_seccion do %>
  Recargas
<% end %>

<%= render "shared/flash", flash: flash %>
<%= render partial: 'recarga_saldos/recargas_formulario', layout: "layouts/formulario",
    locals: {
        registro: @registro,
        url: @url
    }
%>

app/views/recarga_saldos/index.html.erb
<% content_for :titulo_seccion do %>
  Recarga de Saldos
<% end %>

<div class="col-lg-12 col-12">
   <div class="row">
      <%= render 'recarga_saldos/filtros' %>
      <div class="col-lg-6 text-right">
         <%= link_to "Crear recargas", new_recarga_saldo_path, class: "btn btn-lg btn-neutral" %>
      </div>
   </div>
</div>

<div class="container-fluid mt-3">
   <div class="row">
      <div class="col pl-0 pr-0">
         <div class="card">
            <div class="card-header">
               <h3 class="mb-0">Recargas registradas</h3>
            </div>
            <div class="table-responsive">
               <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                     <tr>
                        <th class="sort"><%= sort_link(@coleccion, :fecha, "Fecha") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :usuario_id, "Usuario") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :telefono, "Numero") %></th>
                        <th class="sort"><%= sort_link(@coleccion, :catalogo_recarga_id, "Operación") %></th>
                        <th>Saldo Inicial</th>
                        <th>Saldo Final</th>
                     </tr>
                  </thead>
                  <tbody class="list">
                    <% @registros.each do |recarga| %>
                     <tr>
                        <td><%= recarga.fecha %></td>
                        <td><%= recarga.usuario.usuario %></td>
                        <td><%= recarga.usuario.telefono %></td>
                        <td><%= recarga.catalogo_recarga.nombre %></td>
                        <td><%= recarga.saldo_inicial %></td>        
                        <td><%= recarga.saldo_final%></td>        
                     </tr>
                    <% end %>
                  </tbody>
               </table>
            </div>
            <div class="card-footer py-4">
             <%= paginate @registros %>
             <%= page_entries_info @registros %>
            </div>
         </div>
      </div>
   </div>
</div>